name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - staging  
  workflow_dispatch:  # Allow manual triggers

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: classconnect-staging
  REGION: ${{ secrets.REGION }}
  REPO_NAME: classconnectrepo

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Build and push container
        run: |
          gcloud builds submit --region=${{ env.REGION }} \
            --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --min-instances=0 \
            --max-instances=3 \
            --concurrency=80 \
            --timeout=40m \
            --allow-unauthenticated \
            --set-env-vars=AZURE_SPEECH_KEY=CA4BV9f9rvEKQL22h6L383ucFVNHl9HvkS9bYsBR8xI6cdJm85fHJQQJ99BEACYeBjFXJ3w3AAAYACOGS9sl,AZURE_SPEECH_REGION=eastus,OPENAI_API_KEY=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,SUPABASE_URL=https://drcsbokflpzbhuzsksws.supabase.co,SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyY3Nib2tmbHB6Ymh1enNrc3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDU5MDEsImV4cCI6MjA2MTUyMTkwMX0.yooduUfC1Xecr4LAaIeVA1-BLMe6STQHbzprNt2h6Zs,ASSEMBLYAI_API_KEY=2dbe40dc3dc0413ebf929da37dd61441